name: flutter_movie_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/banner.png
    - assets/images/ellie.png
    - assets/images/eric.png
    - assets/images/jenny.png
    - assets/images/kevin.png
    - assets/images/louis.png
    - assets/images/poster.png
    - assets/images/heidi.jpg
    - assets/images/review_user_avatar.jpg

  fonts:
    - family: CallOfOpsDuty
      fonts:
        - asset: assets/fonts/Call-of-Ops-Duty.ttf
